### ISSUE TITLE
Opt-in to hacktoberfest

### ISSUE THREAD

**Issue by yoursunny** [zyedidia/generic#27]
I'd like to contribute to this repository as part of Hacktoberfest.
In order for the Pull Requests to count toward my Hacktoberfest contributions, it is necessary for the maintainer to add `hacktoberfest` as a repository topic.
Can you do that?
https://hacktoberfest.com/participation/#maintainers

**Comment by zyedidia** [comment]
Sounds good, I have added `hacktoberfest` as a repository topic. Thanks!
