### ISSUE TITLE
Trie implementation is incompatible with non-ASCII characters

### ISSUE THREAD

**Issue by AngusGMorrison** [zyedidia/generic#34]
The current trie implementation fails for Unicode characters greater than 1 byte in size. This is because it indexes string keys directly rather than first converting strings to rune slices, wherein each rune represents a whole Unicode character.

This occurs in both the [get](https://github.com/zyedidia/generic/blob/b8c944db118b8faafcb55913fc04b0380f2545b2/trie/trie.go#L56) and [put](https://github.com/zyedidia/generic/blob/b8c944db118b8faafcb55913fc04b0380f2545b2/trie/trie.go#L91) methods.

If you agree this is a problem, I'm happy to open a PR.

**Comment by zyedidia** [comment]
I think it is just the `KeysWithPrefix` function that was broken with unicode. I pushed a commit that should fix it now, let me know if you are having further problems though. Ideally we can avoid storing runes in the trie to avoid needing to convert strings to slices of runes (the copy/conversion can be costly).

**Comment by AngusGMorrison** [comment]
Ah yes, you're right of course. A trie of bytes will work in just the same way as a tree of runes (apart from the performance difference). Thanks for the patch.
