### ISSUE TITLE
Trie Remove implementation is inefficient

### ISSUE THREAD

**Issue by AngusGMorrison** [zyedidia/generic#35]
The implementation of `(*Trie).Remove` causes the trie to become steadily less efficient as more keys are deleted.

By inserting a tombstone instead of recursively deleting unused nodes, many redundant nodes may remain in place. This increases the the worst-case time for a search miss from logarithmic to linear.

For example, imagine our trie contains only the key "APPLE". We call, `t.Remove("APPLE")`, which replaces the value at the final "E" character with a tombstone. If we now search for "APPLES", we must check the nodes "A", "P", "P", "L" and "E", before finding that "APPLES" is not in the trie, since none of these nodes were deleted when "APPLE" was removed.

What should happen in this scenario is that we delete "APPLE", causing all of its nodes to be recursively deleted from the trie. Now when we search for "APPLES", we immediately miss when looking up the letter "A".

Please correct me if there's a use case for the tombstone that I've misunderstood. Otherwise I'm happy to open a PR to fix this.

**Comment by zyedidia** [comment]
I think the tombstone was mainly just to have simple and fast deletion. Doing a full delete sounds like a better approach, feel free to open a PR for that change.

**Comment by AngusGMorrison** [comment]
Thanks for the reply. I've opened a PR 👍
