### ISSUE TITLE
Add Persistent Rope

### ISSUE THREAD

**Issue by hhhhhhhhhn** [zyedidia/generic#38]
Hello @zyedidia, I was thinking of contributing a persistent rope to the project.

Does it fit in to the project? There is already a rope, but adding immutable methods to it would cause undefined behavior if you used them with the mutable ones.

Thank you for your time!

**Comment by zyedidia** [comment]
I think it might fit. What would the API look like, and how would it be different from the current rope?

**Comment by hhhhhhhhhn** [comment]
It would be pretty similar to the current rope, except operations like insert would return a changed value instead of changing it. For example, instead of:

```go
rope := Rope.New([]int{1,3,4})
rope.Insert(1, []int{2})
rope  // [1, 2, 3, 4]
```

You would have
```go
rope := PRope.New([]int{1,3,4})
changedRope := rope.Insert(1, []int{2})
rope  // [1, 2, 4]
changedRope // [1, 2, 3, 4]
```

The difference is quite minimal, but it can be very useful, specially because creating a copy of the rope takes log(n) instead of n space. I have used this approach in the past for a text editor, and it does not seem to have trouble with slowing the GC either.

**Comment by zyedidia** [comment]
Alright sounds good, let's call the package `prope`.
