### ISSUE TITLE
package "constraints" has been removed since go 1.18 rc1

### ISSUE THREAD

**Issue by junchuanwang** [zyedidia/generic#4]
running into this problem
```
go get -u github.com/zyedidia/generic
github.com/zyedidia/generic imports
	constraints: package constraints is not in GOROOT (/usr/local/go/src/constraints)
```
I confirmed the package is not in the src path.

Then I found the constraints will be removed in 1.18 
see https://github.com/golang/go/issues/50792

**Comment by zyedidia** [comment]
Thank you for reporting this issue, it should be fixed now.
