### ISSUE TITLE
Add Unrolled Linked List

### ISSUE THREAD

**Issue by anandvarma** [zyedidia/generic#45]
Hey @zyedidia, I was thinking of contributing an unrolled linked list implementation.
https://en.wikipedia.org/wiki/Unrolled_linked_list

I am implementing one for another project but thought your repo is probably a good home for it. Let me know if you would like me to work on it and send a PR.

Thanks,
Anand

**Comment by zyedidia** [comment]
Sure if you want to submit a PR I will do my best to review and merge it.

**Comment by anandvarma** [comment]
Thanks @zyedidia, submitted a PR: https://github.com/zyedidia/generic/pull/46
