### ISSUE TITLE
bugfix: you should always check the parameter x1, x2 value of array2d.RowSpan(x1, x2, y int) []T method.

### ISSUE THREAD

**Issue by forbearing** [zyedidia/generic#49]
In array2d.RowSpan(x1, x2, y int) []T method, you should alway check the parameter value of x1 ,x2. it will panic if x2 less than x1.
The solution like below:
![Screenshot 2023-08-14 at 09 17 56](https://github.com/zyedidia/generic/assets/22474410/5f1cbf85-3a4f-435a-8208-8a61e9cbefa6)

**Comment by zyedidia** [comment]
Thanks, closed by #50.
